### ISSUE TITLE
Binding ElementName not working

### ISSUE THREAD

**Issue by ellisonch** [EmptyKeys/UI_Generator#10]
It seems that using `ElementName` in a binding should either generate an error, or it should generate different code.  Currently, it seems to be ignored.

```
<ToggleButton x:Name="CheatButton">Cheat</ToggleButton>
<Popup x:Name="CheatPopup" StaysOpen="False" IsOpen="{Binding ElementName=CheatButton, Path=IsChecked}">
    <TextBlock>FooBarBaz</TextBlock>
</Popup>
```

The above generates the same code as the following (with `ElementName=CheatButton` removed):
```
<ToggleButton x:Name="CheatButton">Cheat</ToggleButton>
<Popup x:Name="CheatPopup" StaysOpen="False" IsOpen="{Binding Path=IsChecked}">
    <TextBlock>FooBarBaz</TextBlock>
</Popup>
```
The code that these both generate is:
```
this.CheatPopup = new Popup();
this.e_6.Children.Add(this.CheatPopup);
this.CheatPopup.Name = "CheatPopup";
Binding binding_CheatPopup_IsOpen = new Binding("IsChecked");
this.CheatPopup.SetBinding(Popup.IsOpenProperty, binding_CheatPopup_IsOpen);
```
which doesn't seem to be using the `ElementName` property.
At runtime, this generates the following error (I assume because `IsChecked` is a property of the `CheatButton`, not of the current `DataContext`)
```
An unhandled exception of type 'System.ArgumentException' occurred in EmptyKeys.UserInterface.dll

Additional information: Binding error: Property Path - Property not found
```
FWIW, it also would be useful to include the property path being looked for in the error, if possible.  E.g., `Additional information: Binding error: Property Path="IsChecked" - Property not found`

**Comment by EmptyKeys** [comment]
ElementName is not supported and It's already in backlog - http://emptykeys.com/Community/aft/12

**Comment by EmptyKeys** [comment]
I didn't find some generic way how to check for unsupported stuff on binding class except IF on each property, which is no go.

I tested current version and information about property path is already present in exception (Parameter name)

`Exception classes:   
   System.ArgumentException
Exception messages:  
   Binding error: Property Path - Property not found
Parameter name: Test
`
