### ISSUE TITLE
multibinding doesn't seem to work

### ISSUE THREAD

**Issue by ellisonch** [EmptyKeys/UI_Generator#12]
I'm trying to format text as described in http://stackoverflow.com/questions/2552853/how-to-bind-multiple-values-to-a-single-wpf-textblock
```
<TextBlock>
    <TextBlock.Text>
        <MultiBinding StringFormat="{}{0} + {1}">
            <Binding Path="Name" />
            <Binding Path="ID" />
        </MultiBinding>
    </TextBlock.Text>
</TextBlock>
```
However, when I compile this, EK doesn't generate any code related to the .Text property of this element.  There also are no warnings or errors.

**Comment by EmptyKeys** [comment]
I'm still considering to support MultiBinding in some future version.

If it's not easy to detect (like attach properties for example) then you will not see any Not Supported error/warning. There is to many features, which are not supported and hard to detect them. I understand it's unfriendly, but I don't have time to deal with them. Feel free to change UI Generator and make pull request.

**Comment by EmptyKeys** [comment]
Done, error is generated in class output for not supported binding type. I will add MultiBinding to backlog.
