### ISSUE TITLE
Failed to create type

### ISSUE THREAD

**Issue by aravol** [EmptyKeys/UI_Generator#14]
When attempting to compile the following

```
<ResourceDictionary x:Class="MyGame.UI.Xaml.Resources"
                    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
                    xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
                    xmlns:local="clr-namespace:MyGame.UI.Xaml"
                    xmlns:vm="clr-namespace:MyGame.UI.ViewModels"
                    mc:Ignorable="d" >
    <DataTemplate DataType="{x:Type vm:SampleViewModel}"/>
</ResourceDictionary>
```

I receive the following error in the resultant file

> #error 'Failed to create a 'Type' from the text 'vm:SampleViewModel'.' Line number '1' and line position '422'.

With a [stack trace](https://github.com/EmptyKeys/UI_Generator/files/115171/StackTrace.txt) shown in the EmptyKeys command line (attached as a file due to formatting issues)

The ViewModel namespace exists in the same assembly as the one being targeted for user interface generation. Using or omitting `assembly` in the `vm` namespace has no effect on the error

**Comment by EmptyKeys** [comment]
Yeah, it's one of the issues with XAML Parser. Move your view model to different project and use assembly in namespace. I didn't find a way how to avoid this.

**Comment by aravol** [comment]
Since the UI project is throwing away the resultant DLL anyway, I'll try turning it on its own output directory and see if that does the trick

**Comment by aravol** [comment]
The above did not work, because WPF does not allow an explicit assembly attribute on xmlns declarations to clr-namespaces in the same assembly, while the XAML parser won't handle clr-namespaces without it.

I can resolve this by adding a da/defaultAssembly parameter, and then using a regex to replace xaml as it's being processed. Expect a merge request.

**Comment by aravol** [comment]
See #15
