### ISSUE TITLE
EKUIGen copying working dir

### ISSUE THREAD

**Issue by aravol** [EmptyKeys/UI_Generator#16]
When using the UI generator, dlls from the Working Directory are copied into the directory of EkUiGen, and left there after compilation takes place.

This is a problem when using a forked version, since these extra files are potentially seen by source control.

**Comment by EmptyKeys** [comment]
I see, pls read this https://docs.nuget.org/consume/package-restore and let me know if this is not part of your scenario and why.

**Comment by aravol** [comment]
This is not part of my scenario since I am using a forked version of the UI generator; this forked version correspond with pull requests #15.

**Comment by EmptyKeys** [comment]
You could make your own local Nuget for your team, it's very simple. Adding DLL's to your source control is just not good idea (except very rare cases).
