### ISSUE TITLE
StyleCop for generated files

### ISSUE THREAD

**Issue by persn** [EmptyKeys/UI_Generator#18]
It would be helpful if generated code files had the following comment at top, so that there aren't thrown hundreds of warnings for those who use common style checkers like Stylecop.

```
// <auto-generated />
```

**Comment by EmptyKeys** [comment]
I will add that to the next version

**Comment by robertkety** [comment]
Presently, the UIGenerator only creates a hard-coded comment section advising against modifying generated code.  Allowing for argument-based custom comment sections would not only provide a solution for the Stylecop issue, but allow users to insert their license, copyright, and other project metadata at the top of the file.

**Comment by EmptyKeys** [comment]
Implementation done, feature will be in the next version (3.0)

**Comment by persn** [comment]
It seems to work great, thank you for your time on this.
