### ISSUE TITLE
OS X / Xamarin Studio compatibility

### ISSUE THREAD

**Issue by PumpkinPaul** [EmptyKeys/UI_Generator#4]
Will the Generator support building on the Mac? Or is the intention to build on Windows and then use the output artifacts in Mac projects?

**Comment by EmptyKeys** [comment]
Unfortunately I'm using XAML reader from WPF and that's not on Mac. So generate UI on Win use everywhere.

**Comment by PumpkinPaul** [comment]
In that case, I may look to provide a web service that could generate them for Mac users.

**Comment by EmptyKeys** [comment]
hmm interesting idea, not sure if there is any XAML editor on mac, maybe Xamarin forms designer could work somehow. Let's investigate :)
