### ISSUE TITLE
Roslyn?

### ISSUE THREAD

**Issue by Michael-DST** [EmptyKeys/UI_Generator#5]
Cool project. :)

Looks like the code generation is based on the older CodeCom model.  Are there plans to leverage/utilize the new Roslyn engine in VS2015?

**Comment by EmptyKeys** [comment]
Thanks. Maybe, tho there is only 1-2 things, which I couldn't properly generate so not sure if it's worth it (as standalone generator). Would be cool to have Roslyn based generator for generating code from XAML in runtime tho.

**Comment by Michael-DST** [comment]
That's sort of what I am aiming for. :)  To be sure... when you say UI Generator... this is the generator that takes a Xaml file and creates the .cs file, correct?

Also, from what what I understand, Roslyn is much faster than CodeDom/previous code-walking APIs.

**Comment by EmptyKeys** [comment]
Yes, that's correct.

Yeah, sure that Roslyn is much faster and on top of that it's actually compiler too. You could use this "old" generator in runtime too. I used that kind of tech in the past, but Roslyn would be better. So maybe in future... :)

**Comment by Michael-DST** [comment]
Yeah I have used CodeCom before and it was not very pleasant.  I wouldn't mind possibly looking into helping move this project to Roslyn. :D

**Comment by EmptyKeys** [comment]
Sure, you can check it out how much work it would be. I knew that one day I might move from old CodeDom so 99% of the methods generating code are in CodeComHelper class. Would be interesting to know if there is anything, which would be problematic with Roslyn gen.

**Comment by Michael-DST** [comment]
cooooool... i'll check it out!
