### ISSUE TITLE
#error This type is not supported - POCO Object

### ISSUE THREAD

**Issue by Mike-EEE** [EmptyKeys/UI_Generator#6]
Hello,

I am attempting to create a Xaml serialization of a POCO object:

```
namespace GameData
{
    public class Testing
    {

        public string PropertyName { get; set; }
    }
}
```

And Xaml:

```
<gameData:Testing
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008" 
    xmlns:gameData="clr-namespace:GameData;assembly=GameData"
    mc:Ignorable="d" 
    PropertyName="Hello World" />
```

Upon generation, I get the following message/error:
2>  Generating C:\Users...\Testing.xaml
2>  #error This type is not supported - GameData.Testing

Is definition/serialization of POCO's supported?  They should be. :smile:  I can see myself defining all sorts of objects in my application using this mechanism, not just UI-centric items.  To be sure, System.Xaml was made into its own assembly so that other non-UI-related applications (Workflow Foundation, for example) can utilize it.  It would be great to see this project take the same approach.

**Comment by EmptyKeys** [comment]
Yeah, it would be cool. Not sure if that's possible without knowing the type in UI Generator. I might think about some "plugin" system tho. 

BTW System.Xaml is useless for cross-platform.

**Comment by Michael-DST** [comment]
I know it is useless that is why I am looking at this project. :)

It should totally be possible to generate a POCO straight up with this generator.  I should start taking a look through its code.

FWIW, there is a bit of demand for a cross-platform System.Xaml:
http://forums.dotnetfoundation.org/t/nature-of-core-net-system-xaml/968
