### ISSUE TITLE
DataTemplates aren't being styled using default styles

### ISSUE THREAD

**Issue by ellisonch** [EmptyKeys/UI_Generator#8]
The following snippet, inside of a ResourceDictionary doesn't seem to be working as expected:         
```
<Style TargetType="{x:Type TextBlock}" BasedOn="{StaticResource {x:Type TextBlock}}">
    <Setter Property="FontFamily" Value="Kootenay"/>
    <Setter Property="FontSize" Value="12"/>
</Style>
<DataTemplate DataType="{x:Type data:CustomWindow}">
    <Border Background="Blue">
        <StackPanel>
            <TextBlock Text="{Binding TextData}" />
        </StackPanel>
    </Border>
</DataTemplate>
```       
                  
The style block is setting the default font for TextBlocks, but the generator isn't taking it into consideration.  When it generates code, it includes both the specified font, as well as the old default font: 

```
FontManager.Instance.AddFont("Tahoma", 11F, FontStyle.Regular, "Tahoma_8.25_Regular");
FontManager.Instance.AddFont("Kootenay", 12F, FontStyle.Regular, "Kootenay_9_Regular");
```   
                  
 However, changing defaults work elsewhere in EK.         
                  
 If instead of trying to set the default, I specify a specific style: 
```
<Style x:Key="NotDefault" TargetType="{x:Type TextBlock}" BasedOn="{StaticResource {x:Type TextBlock}}">
    <Setter Property="FontFamily" Value="Kootenay"/>
    <Setter Property="FontSize" Value="12"/>
</Style>
<DataTemplate DataType="{x:Type data:CustomWindow}">
    <Border Background="Blue">
        <StackPanel>
            <TextBlock Style="{StaticResource NotDefault}" Text="{Binding TextData}" />
        </StackPanel>
    </Border>
</DataTemplate>
```     
the generated code is correct, and only includes a reference to Kootenay.

**Comment by EmptyKeys** [comment]
If you use that first code it works in runtime right? It's using correct font right?

**Comment by ellisonch** [comment]
At runtime, it uses Kootenay.  In fact, it uses it whether or not the style definition comes before or after the data template definition in the file.  I don't know enough about the semantics of this stuff to know if that is correct.

I'm trying to avoid using Tahoma in my game, as it's not a free or open font.  Of course, I could include a fake font as Tahoma , but this would be a workaround.  Just because my current OS/Theme etc dictates that my default style on my development computer uses Tahoma or Times New Roman, 14 or 12 or 10 pt whatever, I'd rather not have to fake EmptyKeys out by giving it fake fonts.

**Comment by ellisonch** [comment]
Actually, I played around with it a little more and there seems to be something else strange going on, with errors at runtime.  If I set a default style with family and size, then specify a specific family:
```
<Style TargetType="{x:Type TextBlock}" BasedOn="{StaticResource {x:Type TextBlock}}">
    <Setter Property="FontFamily" Value="Kootenay"/>
    <Setter Property="FontSize" Value="24"/>
</Style>
<DataTemplate DataType="{x:Type data:CustomWindow}">
    <Border Background="Blue">
        <StackPanel>
            <TextBlock FontFamily="Garrison" Text="{Binding TextData}" />
        </StackPanel>
    </Border>
</DataTemplate>
```

It seems to wind up requesting the made up font at the wrong size:
```
FontManager.Instance.AddFont("Garrison", 11F, FontStyle.Regular, "Garrison_8.25_Regular");
```

I'd expect it to request Garrison24, since that was the default, and it wasn't changed.  If I don't specify `FontFamily="Garrison"`, it correctly requests and uses Kootenay24.

**Comment by EmptyKeys** [comment]
I see, checked code and I know why, but not sure how to fix that at this moment. Think should be possible to get rid of that Tahoma line from first example. Stay tuned :)

**Comment by EmptyKeys** [comment]
Done, default style will not be in generated output anymore. Fix in next version
